# Paths

export TMUX_POWERLINE_RCFILE="$HOME/.tmux-powerlinerc"
export TMUX_POWERLINE_SEGMENTS_HOME="$TMUX_POWERLINE_HOME/segments"
export TMUX_POWERLINE_THEMES_DIRECTORY="$TMUX_POWERLINE_HOME/themes"
export TMUX_POWERLINE_TEMPORARY_DIRECTORY="/tmp/tmux-powerline"

if [ ! -d "$TMUX_POWERLINE_TEMPORARY_DIRECTORY" ]; then
	mkdir "$TMUX_POWERLINE_TEMPORARY_DIRECTORY"
fi
