###
# Default Theme
#
if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
  export TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
    "tmux_session_info 234 148" \
    "hostname 33 0" \
    "lan_ip 24 255" \
    "wan_ip 24 255" \
    "vcs_branch 29 88" \
    "vcs_compare 60 255" \
    "vcs_staged 64 255" \
    "vcs_modified 9 255" \
    "vcs_others 245 0" \
  )
fi

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
  export TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
    "pwd 234 255" \
    "mail_count_gmail 33 255" \
    "np_mpd 234 37" \
    "cpu 24 255" \
    "load 29 255" \
    "battery 60 255" \
    "weather_yahoo 37 255" \
    "date_day 9 255" \
    "date_full 37 255" \
    "time 235 255" \
  )
fi

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=235
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=255

if patched_font_in_use; then
  TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="⮂"
  TMUX_POWERLINE_SEPARATOR_LEFT_THIN="⮃"
  TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="⮀"
  TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="⮁"
else
  TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
  TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
  TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
  TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD
