# Prints the week of the current year.
TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL="${TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL:-󰨳}"
TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL_COLOUR="${TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL_COLOUR:-255}"


generate_segmentrc() {
	read -d '' rccontents  << EORC
# Symbol for calendar week.
# export TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL="${TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL}"
# export TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL_COLOUR="${TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL_COLOUR}"
EORC
	echo "$rccontents"
}

run_segment() {
	__process_settings
  echo "#[fg=colour${TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL_COLOUR}]${TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL} #[fg=${TMUX_POWERLINE_CUR_SEGMENT_FG}]$(date +"%W")"
	return 0
}

__process_settings() {
	if [ -z "$TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL" ]; then
		export TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL="${TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL}"
	fi
	if [ -z "$TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL_COLOUR" ]; then
		export TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL_COLOUR="${TMUX_POWERLINE_SEG_DATE_WEEK_SYMBOL_COLOUR}"
	fi
}
