#!/usr/bin/env osascript
# Returns the current playing song in iTunes for macOS.

tell application "System Events"
	set process_list to (name of every process)
end tell

if process_list contains "iTunes" then
	tell application "iTunes"
		if player state is playing then
			set track_name to name of current track
			set artist_name to artist of current track
			#			set album_name to album of current track
			set now_playing to artist_name & " - " & track_name
		end if
	end tell
end if
