#!/usr/bin/osascript
set mail_running to is_running("Mail")

if mail_running
	tell application "Mail"
	   set a to unread count of inbox
	end tell
end if

on is_running(appName)
  tell application "System Events" to (name of processes) contains appName
end is_running
